#### COMMENTS
- according to the publication, three classes are present (https://pubmed.ncbi.nlm.nih.gov/30220217/)
- *H: Tox < 1 μg/bee; M: 1 μg/bee < Tox < 100 μg/bee; L: Tox > 100 μg/bee.

In [1]:
import pandas as pd

In [2]:
data = pd.read_excel('data.xlsx')

In [3]:
data.head()

,ID,Cas NUMBER,SMILES,Experimental value LD 50 [μg/bee],Dataset,C1-1,Unnamed: 6,C100-2,Unnamed: 8,Toxicity level
0,1,52918-63-5,CC1(C)C(C=C(Br)Br)C1C(=O)OC(C#N)c1cccc(Oc2cccc...,"0,0015",tr,1,NaN,-,NaN,H
1,2,131929-60-7,CCC1CCCC(OC2CCC(C(C)O2)N(C)C)C(C)C(=O)C2=CC3C4...,"0,0029",tr,1,NaN,-,NaN,H
2,3,80844-07-1,CCOc1ccc(cc1)C(C)(C)COCc1cccc(Oc2ccccc2)c1,"0,0145",tr,1,NaN,-,NaN,H
3,4,66841-24-5,CC1(C)C(C=C(Cl)Cl)C1C(=O)OC(C#N)c1cccc(Oc2cccc...,"0,023",tr,1,NaN,-,NaN,H
4,5,52645-53-1,CC1(C)C(C=C(Cl)Cl)C1C(=O)OCc1cccc(Oc2ccccc2)c1,"0,024",v,1,NaN,-,NaN,H

In [4]:
activity = []
for row in data['Toxicity level']:
    if row == "H":
        activity.append(1)
    if row == "M":
        activity.append(0.5)
    if row == "L":
        activity.append(0)

In [5]:
len(activity)

254

In [6]:
len(data['Toxicity level'])

254

In [7]:
data['activity'] = activity

In [8]:
to_be_printed = data[['SMILES','activity']]

In [9]:
to_be_printed

                                                SMILES  activity
0    CC1(C)C(C=C(Br)Br)C1C(=O)OC(C#N)c1cccc(Oc2cccc...       1.0
1    CCC1CCCC(OC2CCC(C(C)O2)N(C)C)C(C)C(=O)C2=CC3C4...       1.0
2           CCOc1ccc(cc1)C(C)(C)COCc1cccc(Oc2ccccc2)c1       1.0
3    CC1(C)C(C=C(Cl)Cl)C1C(=O)OC(C#N)c1cccc(Oc2cccc...       1.0
4       CC1(C)C(C=C(Cl)Cl)C1C(=O)OCc1cccc(Oc2ccccc2)c1       1.0
..                                                 ...       ...
249                       OC(=O)c1c(Cl)ccc2cc(Cl)cnc12       0.0
250   CCc1ccc(cc1)C(=O)NN(C(=O)c1cc(C)cc(C)c1)C(C)(C)C       0.0
251             Clc1ccc(CCC(Cn2cncn2)(C#N)c2ccccc2)cc1       1.0
252                          Clc1ccc(CN2CCSC2=NC#N)cn1       0.0
253   COc1ncc(F)c2[nH]c(n[n+]12)S(=O)(=O)Nc1c(F)cccc1F       1.0

[254 rows x 2 columns]

In [10]:
to_be_printed[to_be_printed['activity'] == 0.5]

                                                SMILES  activity
19      ClC1=C(Cl)C2(Cl)C3C4CC(C5OC45)C3C1(Cl)C2(Cl)Cl       0.5
20                         CNC(=O)Oc1cccc2CC(C)(C)Oc12       0.5
38                        COP(=O)(OC)OC(Br)C(Cl)(Cl)Br       0.5
39                               COP(=O)(OC)OC=C(Cl)Cl       0.5
43   CC(C)C(Nc1ccc(cc1Cl)C(F)(F)F)C(=O)OC(C#N)c1ccc...       0.5
..                                                 ...       ...
226                [O-][n+]1nc(nc2ccc(Cl)cc12)-n1ccnc1       0.5
228                 CC1(CCCCC1)C(=O)Nc1ccc(O)c(Cl)c1Cl       0.5
229                      NC1=C(Cl)C(=O)N(N=C1)c1ccccc1       0.5
232                   CN1C(=O)ON(C1=O)c1ccc(Cl)c(Cl)c1       0.5
248                   ClC(Cl)(Cl)SN1C(=O)C2CC=CCC2C1=O       0.5

[69 rows x 2 columns]

In [11]:
to_be_printed[to_be_printed['activity'] == 1]

                                                SMILES  activity
0    CC1(C)C(C=C(Br)Br)C1C(=O)OC(C#N)c1cccc(Oc2cccc...       1.0
1    CCC1CCCC(OC2CCC(C(C)O2)N(C)C)C(C)C(=O)C2=CC3C4...       1.0
2           CCOc1ccc(cc1)C(C)(C)COCc1cccc(Oc2ccccc2)c1       1.0
3    CC1(C)C(C=C(Cl)Cl)C1C(=O)OC(C#N)c1cccc(Oc2cccc...       1.0
4       CC1(C)C(C=C(Cl)Cl)C1C(=O)OCc1cccc(Oc2ccccc2)c1       1.0
..                                                 ...       ...
241  CCC(C)(C)C(=O)OC1=C(C(=O)OC11CCCCC1)c1cc(Cl)cc...       1.0
246              Clc1ccc(cc1)-c1ccccc1NC(=O)c1cccnc1Cl       1.0
247                    CCOC(=O)NCCOc1ccc(Oc2ccccc2)cc1       1.0
251             Clc1ccc(CCC(Cn2cncn2)(C#N)c2ccccc2)cc1       1.0
253   COc1ncc(F)c2[nH]c(n[n+]12)S(=O)(=O)Nc1c(F)cccc1F       1.0

[91 rows x 2 columns]

In [12]:
to_be_printed[to_be_printed['activity'] == 0]

                                                SMILES  activity
47               COP(=O)(OC)OC(=CCl)c1cc(Cl)c(Cl)cc1Cl       0.0
56   COc1cc(OC)nc(Oc2cccc(Oc3nc(OC)cc(OC)n3)c2C(O)=...       0.0
69    CCOC(=O)c1ccccc1S(=O)(=O)NC(=O)Nc1nc(Cl)cc(OC)n1       0.0
73                                Oc1c(Br)cc(cc1Br)C#N       0.0
75                            OC(=O)CCCOc1ccc(Cl)cc1Cl       0.0
..                                                 ...       ...
244  [O-][N+](=O)c1cc(c(Cl)c(c1Nc1ncc(cc1Cl)C(F)(F)...       0.0
245   CON=C(C(=O)OC)c1ccccc1CON=C(C)c1cccc(c1)C(F)(F)F       0.0
249                       OC(=O)c1c(Cl)ccc2cc(Cl)cnc12       0.0
250   CCc1ccc(cc1)C(=O)NN(C(=O)c1cc(C)cc(C)c1)C(C)(C)C       0.0
252                          Clc1ccc(CN2CCSC2=NC#N)cn1       0.0

[94 rows x 2 columns]

In [13]:
to_be_printed = to_be_printed.rename(columns={'SMILES': 'SMILES', 'activity': 'target_0'})

In [14]:
to_be_printed.head()

                                              SMILES  target_0
0  CC1(C)C(C=C(Br)Br)C1C(=O)OC(C#N)c1cccc(Oc2cccc...       1.0
1  CCC1CCCC(OC2CCC(C(C)O2)N(C)C)C(C)C(=O)C2=CC3C4...       1.0
2         CCOc1ccc(cc1)C(C)(C)COCc1cccc(Oc2ccccc2)c1       1.0
3  CC1(C)C(C=C(Cl)Cl)C1C(=O)OC(C#N)c1cccc(Oc2cccc...       1.0
4     CC1(C)C(C=C(Cl)Cl)C1C(=O)OCc1cccc(Oc2ccccc2)c1       1.0

In [15]:
to_be_printed.to_csv('data.csv')

In [16]:
#to_be_printed.to_csv('Toxicity_in_honeybees.csv')

## AGG

In [17]:
import pandas as pd
import numpy as np
data_ = pd.read_csv('data.csv')
data_.head()

   Unnamed: 0                                             SMILES  target_0
0           0  CC1(C)C(C=C(Br)Br)C1C(=O)OC(C#N)c1cccc(Oc2cccc...       1.0
1           1  CCC1CCCC(OC2CCC(C(C)O2)N(C)C)C(C)C(=O)C2=CC3C4...       1.0
2           2         CCOc1ccc(cc1)C(C)(C)COCc1cccc(Oc2ccccc2)c1       1.0
3           3  CC1(C)C(C=C(Cl)Cl)C1C(=O)OC(C#N)c1cccc(Oc2cccc...       1.0
4           4     CC1(C)C(C=C(Cl)Cl)C1C(=O)OCc1cccc(Oc2ccccc2)c1       1.0

In [18]:
data_['SMILES'].describe()

count                                                254
unique                                               253
top       ClC1=C(Cl)C2(Cl)C3C4CC(C5OC45)C3C1(Cl)C2(Cl)Cl
freq                                                   2
Name: SMILES, dtype: object

In [19]:
data_grouped = data_.groupby('SMILES')

In [20]:
## Helping functions
def get_levels(x):
    y = x.dropna()
    if y.empty:
        return np.nan
    else:
        levs = list(set(y.tolist()))
        if len(levs) == 1:
            return levs[0]
        else:
            return 'mix'

def get_all_levels(x):
    y = x.dropna()
    if y.empty:
        return np.nan
    else:
        return sorted(list(set(y.tolist())))
                
def get_mean(x):
    y = x.dropna()
    if y.empty:
        return np.nan
    else:
        return np.mean(y)
    
def expand_activity(x):
    expanded = [None for iii in range(max_level_activity)]
    n_act = len(x)
    expanded[:n_act] = x[:n_act]
    return np.array(expanded)

In [21]:
aggFunctions = {
    'target_0': ['min', 'max', get_all_levels, get_mean],
    'SMILES': get_levels
}
data_aggregated = data_grouped.agg(aggFunctions)
max_level_activity = max(data_aggregated[("target_0", "get_all_levels")].apply(lambda x: len(x)))
data_aggregated.columns = [str(item[0])+"_"+str(item[1]) for item in data_aggregated.columns.to_flat_index().to_list()]
all_activities = data_aggregated[("target_0_get_all_levels")].apply(lambda x: expand_activity(x))
all_activities = pd.DataFrame(all_activities.to_list(), columns=["target_"+str(iii) for iii in range(max_level_activity)])
all_activities = all_activities.set_index(data_aggregated.index)
data_aggregated = pd.concat([data_aggregated, all_activities], axis=1)
data_aggregated

,target_0_min,target_0_max,target_0_get_all_levels,target_0_get_mean,SMILES_get_levels,target_0
SMILES,,,,,,
C1CN2ccccc2c2ccccN12,0.5,0.5,[0.5],0.5,C1CN2ccccc2c2ccccN12,0.5
C1C[n+]2ccccc2-c2cccc[n+]12,0.5,0.5,[0.5],0.5,C1C[n+]2ccccc2-c2cccc[n+]12,0.5
CC(C)(C)C(O)C(Oc1ccc(Cl)cc1)n1cncn1,0.0,0.0,[0.0],0.0,CC(C)(C)C(O)C(Oc1ccc(Cl)cc1)n1cncn1,0.0
CC(C)(C)N(NC(=O)c1ccc(Cl)cc1)C(=O)c1ccccc1,0.0,0.0,[0.0],0.0,CC(C)(C)N(NC(=O)c1ccc(Cl)cc1)C(=O)c1ccccc1,0.0
CC(C)(C)c1ccc(OC2CCCCC2OS(=O)OCC#C)cc1,0.5,0.5,[0.5],0.5,CC(C)(C)c1ccc(OC2CCCCC2OS(=O)OCC#C)cc1,0.5
...,...,...,...,...,...,...
SC(=S)NCCNC(S)=S,0.5,0.5,[0.5],0.5,SC(=S)NCCNC(S)=S,0.5
[O-][N+](=O)N=C1NCCN1Cc1ccc(Cl)nc1,1.0,1.0,[1.0],1.0,[O-][N+](=O)N=C1NCCN1Cc1ccc(Cl)nc1,1.0
[O-][N+](=O)c1c(Cl)c(Cl)c(Cl)c(Cl)c1Cl,1.0,1.0,[1.0],1.0,[O-][N+](=O)c1c(Cl)c(Cl)c(Cl)c(Cl)c1Cl,1.0
[O-][N+](=O)c1cc(c(Cl)c(c1Nc1ncc(cc1Cl)C(F)(F)F)[N+]([O-])=O)C(F)(F)F,0.0,0.0,[0.0],0.0,[O-][N+](=O)c1cc(c(Cl)c(c1Nc1ncc(cc1Cl)C(F)(F)...,0.0
[O-][n+]1nc(nc2ccc(Cl)cc12)-n1ccnc1,0.5,0.5,[0.5],0.5,[O-][n+]1nc(nc2ccc(Cl)cc12)-n1ccnc1,0.5

In [22]:
data_aggregated.columns.to_list()

['target_0_min',
 'target_0_max',
 'target_0_get_all_levels',
 'target_0_get_mean',
 'SMILES_get_levels',
 'target_0']

In [23]:
to_be_saved_ = data_aggregated.columns.to_list()[5:]

In [24]:
to_save = data_aggregated[to_be_saved_]

In [25]:
to_save.reset_index()

                                                SMILES  target_0
0                                 C1CN2ccccc2c2ccccN12       0.5
1                          C1C[n+]2ccccc2-c2cccc[n+]12       0.5
2                  CC(C)(C)C(O)C(Oc1ccc(Cl)cc1)n1cncn1       0.0
3           CC(C)(C)N(NC(=O)c1ccc(Cl)cc1)C(=O)c1ccccc1       0.0
4               CC(C)(C)c1ccc(OC2CCCCC2OS(=O)OCC#C)cc1       0.5
..                                                 ...       ...
248                                   SC(=S)NCCNC(S)=S       0.5
249                 [O-][N+](=O)N=C1NCCN1Cc1ccc(Cl)nc1       1.0
250             [O-][N+](=O)c1c(Cl)c(Cl)c(Cl)c(Cl)c1Cl       1.0
251  [O-][N+](=O)c1cc(c(Cl)c(c1Nc1ncc(cc1Cl)C(F)(F)...       0.0
252                [O-][n+]1nc(nc2ccc(Cl)cc12)-n1ccnc1       0.5

[253 rows x 2 columns]

In [26]:
to_save.to_csv('data_agg.csv')