Trainig data is prepared manually, due to very badly preapred materials...

In [1]:
import pandas as pd

In [2]:
data = pd.read_excel('data_raw.csv')

In [3]:
data

              NAME  MELTING POINT
0         buramate           40.0
1       fenpiprane           41.0
2     trimipramine           45.0
3    phencarbamide           48.0
4      banactyzine           51.0
..             ...            ...
272      primidone          281.0
273       prazosin          285.0
274     acedapsone          289.0
275      phenytoin          295.0
276    orotic acid          345.0

[277 rows x 2 columns]

In [4]:
import pubchempy as pcp

In [5]:
compounds_l = []
for name in data['NAME']:
    try:
        
        compound = pcp.get_compounds(name, 'name')
        compounds_l.append(compound)
    except:
        
        print("Not found : "+str(name))
compounds_l[0:5]

[[Compound(20787)], [Compound(197785)], [Compound(5584)], [Compound(6008)], []]

In [6]:
data['ID'] = compounds_l

In [7]:
data.head()

            NAME  MELTING POINT                  ID
0       buramate           40.0   [Compound(20787)]
1     fenpiprane           41.0  [Compound(197785)]
2   trimipramine           45.0    [Compound(5584)]
3  phencarbamide           48.0    [Compound(6008)]
4    banactyzine           51.0                  []

In [8]:
isomeric_smiles = []
for compound in data['ID']:
    try:
        
        isomeric_smiles.append(compound[0].isomeric_smiles)
    except:
        isomeric_smiles.append('ERROR')
isomeric_smiles[0:5]

['C1=CC=C(C=C1)CNC(=O)OCCO',
 'C1CCN(CC1)CCC(C2=CC=CC=C2)C3=CC=CC=C3',
 'CC(CN1C2=CC=CC=C2CCC3=CC=CC=C31)CN(C)C',
 'CCN(CC)CCSC(=O)N(C1=CC=CC=C1)C2=CC=CC=C2',
 'ERROR']

In [9]:
isomeric_smiles

['C1=CC=C(C=C1)CNC(=O)OCCO',
 'C1CCN(CC1)CCC(C2=CC=CC=C2)C3=CC=CC=C3',
 'CC(CN1C2=CC=CC=C2CCC3=CC=CC=C31)CN(C)C',
 'CCN(CC)CCSC(=O)N(C1=CC=CC=C1)C2=CC=CC=C2',
 'ERROR',
 'CCN(CC)C(C)CN1C2=CC=CC=C2SC3=CC=CC=C31',
 'CC1=C(C(=CC=C1)OCC(CNC(C)(C)C)O)C',
 'CC(CN1C2=CC=CC=C2SC3=CC=CC=C31)N(C)C',
 'CC1=CC(=C(C=C1)C)OCCCC(C)(C)C(=O)O',
 'C1[C@H]([C@@H]2[C@H](O1)[C@H](CO2)O)O',
 'COC1=CC=CC=C1N2CCN(CC2)CCCC(=O)C3=CC=C(C=C3)F',
 'CC(C)(C)NC[C@@H](COC1=CC=CC=C1C2CCCC2)O',
 'CN/C(=C\\[N+](=O)[O-])/NCCSCC1=CC=C(O1)CN(C)C',
 'CCC(=O)O[C@](CC1=CC=CC=C1)(C2=CC=CC=C2)[C@H](C)CN(C)C',
 'CCC(CC)(CC=C)C(=O)N',
 'CCC(=O)C(CC(C)N1CCOCC1)(C2=CC=CC=C2)C3=CC=CC=C3',
 'CC(C)CC1=CC=C(C=C1)C(C)C(=O)O',
 'CCC(C)C(C)(COC(=O)N)COC(=O)N',
 'CCC1=NC(=C2C=C(C(=CC2=C1)OC)OC)CC3=CC=CC=C3',
 'CCNC1=NSC2=CC=CC=C21',
 'CC(=O)CCC1=CC2=C(C=C1)C=C(C=C2)OC',
 'CC(C)(C)NCC(COC1=C(C=CC(=C1)Cl)Cl)O',
 'CCCCCCN1C(=O)C2=C(N=CN2C)N(C1=O)C',
 'CCC(=O)N(C1CCN(CC1)CCC2=CC=CC=C2)C3=CC=CC=C3',
 'COC(CN1CCN(CC1)CC(C(C2=CC=CC=C2)OC)O)C3=CC=CC=C3',
 'CCOC(=O)C1(CCN(CC1)CCC2=CC=C(C=C2)N)C3=CC=CC=C3',
 'CC(CC1=CC=CC=C1)NC(C#N)C2=CC=CC=C2',
 'CCN1/C(=C/C(=O)OCC)/SC(C1=O)N2CCCCC2',
 'C1=CC(=CC=C1COC(CN2C=CN=C2)C3=C(C=C(C=C3)Cl)Cl)Cl',
 'CCN(CC)CCCC(C)NC1=C2C=CC(=CC2=NC=C1)Cl',
 'CN1CCC(C1)CN2C3=CC=CC=C3SC4=CC=CC=C42',
 'CNC(=S)NCO',
 'CC(C)(C)NCC(C1=CC=CC=C1Cl)O',
 'CC(=O)SCC(CC1=CC=CC=C1)C(=O)NCC(=O)OCC2=CC=CC=C2',
 'CN(C)CCOC1=CC2=CC=CC=C2SC3=C1C=C(C=C3)Cl',
 'CCCC(C)C1(C(=O)NC(=O)NC1=O)C=C',
 'CN1CCC2=C(C1)C(C3=CC=CC=C23)C4=CC=CC=C4',
 'CCCC(C)(COC(=O)N)COC(=O)NC(C)C',
 'ERROR',
 'CNCCCC12CCC(C3=CC=CC=C31)C4=CC=CC=C24',
 'CC1=CC(=CC=C1)N(C)C(=S)OC2=CC3=C(CCC3)C=C2',
 'C1CN(CCN1CCCN2C3=CC=CC=C3SC4=C2C=C(C=C4)Cl)CCO',
 'CC(C1=CC(=CC=C1)C(=O)C2=CC=CC=C2)C(=O)O',
 'CN1CCC(CC1)N(CC2=CC=CS2)C3=CC=CC=C3',
 'COC1=CC(=CC(=C1O)C(=O)NCCO)CC=C',
 'ERROR',
 'CCN(CC1=CC=NC=C1)C(=O)C(CO)C2=CC=CC=C2',
 'CCCC[C@H](C)C[C@@H](/C=C/[C@H]1[C@@H](CC(=O)[C@@H]1CCCC/C=C/C(=O)O)O)O',
 'CC(C)NCC(C1=CC(=CC(=C1)O)O)O',
 'CCC1=C(NC2=C1C=C(C=C2)N(C)C)C',
 'CC(C)(C(=O)NC(=O)NCN1CCOCC1)OC2=CC=C(C=C2)Cl',
 'CCC(C1=CC=CC=C1)C(=O)NC(=O)NC(=O)C',
 'CCOC1=CC=C(C=C1)NC(=O)CN',
 'CCN(CC)CCNC1=C2C(=C(C=C1)CO)SC3=CC=CC=C3C2=O',
 'CCC1(C(=O)CCNC1=O)CC',
 'CC(COC1=CC=CC=C1)NC(C)C(C2=CC=C(C=C2)O)O',
 'CCCC(C)(COC(=O)N)COC(=O)N',
 'C1CCN(C(C1)C(C2=CC=CC=C2)C3=CC=CC=C3)CCO',
 'C1CN(CCN1C(=O)CCBr)C(=O)CCBr',
 'CC1=CC(=NN1)CCN2CCN(CC2)C3=CC(=CC=C3)Cl',
 'CC1=CN(C(=O)NC1=O)[C@H]2C[C@@H]([C@H](O2)CO)N=[N+]=[N-]',
 'CCCCN1CCCCC1C(=O)NC2=C(C=CC=C2C)C',
 'C1=CC=C(C=C1)CN(C/C(=N/O)/N)C2=CC=CC=C2',
 'CN(C)CCOC1=CC=C(C=C1)/C(=C(/CCCl)\\C2=CC=CC=C2)/C3=CC=CC=C3',
 'CCC(CC)(C(=O)NC(=O)NC(=O)C)Br',
 'CCN(CC)C(=O)NC1=CC(=C(C=C1)OCC(CNC(C)(C)C)O)C(=O)C',
 'CC(C1=CC(=C(C=C1)C2=CC=CC=C2)F)C(=O)O',
 'C1=CC=C2C(=C1)C(=O)N(C2=O)CCCCCOC3=CC=C(C=C3)N',
 'CCC(C)C(CC)C(=O)N',
 'C1=CC=C(C=C1)/C(=C\\CCCCC(=O)O)/C2=CN=CC=C2',
 'CC(C(C1=CC=C(C=C1)O)O)N2CCC(CC2)CC3=CC=CC=C3',
 'CN1[C@@H]2CC[C@H]1CC(C2)OC(=O)C(CO)C3=CC=CC=C3',
 'CC1=C(C(=CC=C1)CC2=CN=CN2)C',
 'CN1CCC(CC1)N(CC2=CC=CC=C2)C3=CC=CC=C3',
 'CCOC(=O)NC1=C(N=C(C=C1)NCC2=CC=C(C=C2)F)N',
 'CC(C)OC1=CC2=C(C=C1)C(=O)C(=CO2)C3=CC=CC=C3',
 'C1C(OCC(=O)N1)C2=CC=C(C=C2)C(F)(F)F',
 'CN1C2=CC=CC=C2C(=O)N(C3=CC=CC=C31)CCN(C)C',
 'CCCCC(=O)N(CC1=CC=C(C=C1)C2=CC=CC=C2C3=NNN=N3)[C@@H](C(C)C)C(=O)O',
 'C1CN(CCC1O)CCCN2C3=CC=CC=C3SC4=C2C=C(C=C4)C#N',
 'C1CC(N2C=NC=C2C1)C3=CC=C(C=C3)C#N',
 'CC1=CC=C(C=C1)C2(CCN(CC2)CCCC(=O)C3=CC=C(C=C3)F)O',
 'C1CC1CN2C(=O)CN=C(C3=C2C=CC(=C3)Cl)C4=CC=CC=C4F',
 'C1COCCN1CNC(=O)C2=NC=CN=C2',
 'CCCC(=O)NC1=CC(=C(C=C1)OCC(CNC(C)C)O)C(=O)C',
 'CC(C)(C)NCC(C1=CC(=CC(=C1)O)O)O',
 'COC1=CC(=CC(=C1OC)OC)C(=O)OCC2=NC(=CC=C2)COC(=O)C3=CC(=C(C(=C3)OC)OC)OC',
 'CN(C)CCC(C1=CC=CC=C1)(C2=CC=CC=C2Cl)O',
 'C1CCN(CC1)CCC(C2=CC=CC=C2)(C3=CC=CC=C3)O',
 'C1CN=C(N1)CN(CC2=CC=CC=C2)C3=CC=CC=C3',
 'CCN1CCC2=C3C1CC=C(N3C4=CC=CC=C24)C(=O)OC',
 'COC1=CC(=CC(=C1OC)OC)C(=O)NCCCCCC(=O)O',
 'C1=CC=C(C=C1)C2=CC=C(C=C2)CC(=O)NC3=CC=CC=N3',
 'CC(CN1C2=CC=CC=C2NC3=C(C1=O)C=CC=N3)N(C)C',
 'C1=CC=C(C=C1)C(=O)O',
 'CCCCNCC(C1=CC=C(C=C1)O)O',
 'CC(C)(C)NCC(COC1=CC=CC2=C1C[C@@H]([C@@H](C2)O)O)O',
 'CCC1=C(C2=CC=CC=C2O1)C(=O)C3=CC=C(C=C3)O',
 'CC(C1=NCCN1)OC2=C(C=CC=C2Cl)Cl',
 'CC1=NC2=CC=CC=C2C(=O)N1C3=CC=CC=C3Cl',
 'CC1=C(C(=O)C(=C(C1=O)C)C(CCCCCC(=O)O)C2=CC=CC=C2)C',
 'CCCC1=CC(=C(C=C1)OCC(=O)N2CCN(CC2)C(=O)COC3=C(C=C(C=C3)CCC)OC)OC',
 'COCC(=O)NC1=C(C=CC(=C1)SC2=CC=CC=C2)N=C(NC(=O)OC)NC(=O)OC',
 'C1CN=C(N1)NC2=C(C=CC=C2Cl)Cl',
 'CC1=CC(=CC(=C1CC2=NCCN2)C)C(C)(C)C',
 'CN(C)C1=NC(=O)C(O1)C2=CC=CC=C2',
 'ERROR',
 'CCC1(C(=O)N(C(=O)N1)C)C2=CC=CC=C2',
 'C1C(OC(=N1)N)C2=CC=CC=C2',
 'C1CCC(CC1)C(=O)N2CC3C4=CC=CC=C4CCN3C(=O)C2',
 'C1CN(CCN1CCCCN2C(=O)C3=CC=CC=C3S2(=O)=O)C4=NC=CC=N4',
 'CC(C)CC1(C(=O)NC(=O)NC1=O)CC=C',
 'CC1=CC=CC=C1S(=O)(=O)NC(=O)C2=CC(=C(C=C2)CC3=CN(C4=C3C=C(C=C4)NC(=O)OC5CCCC5)C)OC',
 'COC1=CC2=C(C=C1C(=O)NCC3CCCN3CC=C)NN=N2',
 'C1=CC=C(C=C1)N=NC2=C(N=C(C=C2)N)N',
 'CCCN(CCC)C(=O)CC1=C(N=C2N1C=C(C=C2)Cl)C3=CC=C(C=C3)Cl',
 'C1COC(=O)C2=CC=CC(=C21)C=O',
 'CC1=C(N=CN1)CSCCNC(=NC)NC#N',
 'C[C@]12CC[C@H]3[C@H]([C@@H]1CC[C@]2(C#C)O)CCC4=C3C=CC(=C4)O',
 'CCOC(=O)CSCCC1NC(CS1)C(=O)O',
 'CCCN(CCC)C(=O)C(CCC(=O)O)NC(=O)C1=CC=CC=C1',
 'CC(C)(C1=CC=C(C=C1)C(CCCN2CCC(CC2)C(C3=CC=CC=C3)(C4=CC=CC=C4)O)O)C(=O)O',
 'CNC(=O)OC1=CC=CC2=CC=CC=C21',
 'CC(=O)OC1=CC=CC=C1C(=O)O',
 'CN(C)CC(=O)N1C2=CC=CC=C2SC3=CC=CC=C31',
 'CCCCNC(=O)NS(=O)(=O)C1=CC=C(C=C1)N',
 'CN1C2=C(C(=O)N(C1=O)C)N(C=N2)CC3OCCO3',
 'ERROR',
 'CC(C)NCC(COC1=CC=C(C=C1)CC(=O)N)O',
 'C1=CC2=C(C(=C1)Cl)SC=C2COC(CN3C=CN=C3)C4=C(C=C(C=C4)Cl)Cl',
 'CC(=O)N1CCN(CC1)C2=CC=C(C=C2)OC[C@@H]3CO[C@@](O3)(CN4C=CN=C4)C5=C(C=C(C=C5)Cl)Cl',
 'CCN(CC)CCNC(=O)C1=CC(=C(C=C1OC)N)Cl',
 'C1=CC=NC(=C1)C(=C2C=CC(=C2)C(C3=CC=CC=N3)(C4=CC=CC=N4)O)C5=CC=CC=N5',
 'C1=CC=C(C=C1)C(C2=CC=CC=C2)(C3=CC=CC=C3Cl)N4C=CN=C4',
 'C1CN(CCC1(C2=CC=C(C=C2)Cl)O)CCCC(=O)C3=CC=C(C=C3)F',
 'C=CCC1(C(=O)NC(=S)NC1=O)C2CCCC=C2',
 'CC(=O)NC(=O)C1=CC=CC=C1O',
 'C/C(=C\\C(=O)O)/C1=C(C=C(C=C1)OC)OC',
 'CC1C(OCCN1CC2=C(N(N(C2=O)C3=CC=CC=C3)C)C)C4=CC=CC=C4',
 'C1=CC=C(C(=C1)CC(=O)OCC(=O)O)NC2=C(C=CC=C2Cl)Cl',
 'COC1=CC=C(C=C1)CCN2CCC(CC2)NC3=NC4=CC=CC=C4N3CC5=CC=C(C=C5)F',
 'ERROR',
 'CC1=C(C2=C(N1C(=O)C3=CC=C(C=C3)Cl)C=CC(=C2)OC)CC(=O)OCC(=O)O',
 'C1=CC=C(C=C1)C(COC(=O)N)COC(=O)N',
 'C1=CC(=CC=C1CN)S(=O)(=O)N',
 'C1N(CSC(=S)N1CC2=CC=CC=C2)CC(=O)O',
 'C[C@@H](C1=CC2=C(C=C1)C=C(C=C2)OC)C(=O)O',
 'COCCOC1=CN=C(N=C1)NS(=O)(=O)C2=CC=CC=C2',
 'CCCCOC1=CC=C(C=C1)CC(=O)NO',
 'CS(=O)(=O)C1=CC=C(C=C1)[C@H]([C@@H](CF)NC(=O)C(Cl)Cl)O',
 'C[C@]12CC[C@H]3[C@H]([C@@H]1CC[C@@H]2O)CCC4=CC(=O)CC[C@]34C',
 'C1CS(=O)(=O)NCN1CN2CCS(=O)(=O)NC2',
 'C[C@H](C[C@@](C1=CC=CC=C1)(C2=CC=CC=N2)C(=O)N)N(C)C',
 'CCC(=O)C1(CCN(CC1)C)C2=CC(=CC=C2)O',
 'CCC1(C(=O)NC(=O)NC1=O)CCC(C)C',
 'C1CSC(=O)C1NC(=O)CSCC(=O)O',
 'C1CN(CCC1C2(CCC(=O)NC2=O)C3=CC=CC=C3)CC4=CC=CC=C4',
 'CN1C(=CC(=O)N(C1=O)C)NCCCN2CCN(CC2)C3=CC=CC=C3OC',
 'CC1=C(C2=CC=CC=C2S1)CC3=NCCN3',
 'CC1=CN=C(C(=C1OC)C)CS(=O)C2=NC3=C(N2)C=C(C=C3)OC',
 'C=CCC1(C(=O)NC(=O)NC1=O)C2=CC=CC=C2',
 'CCOC(=O)NC1=CC2=C(C=C1)SC3=CC=CC=C3N2C(=O)CCN4CCOCC4',
 'CC(C1=CC2=CC=CC=C2S1)N(C(=O)N)O',
 'C1=CC(=CC=C1N)S(=O)(=O)C2=CC=C(C=C2)NC(=O)CCC(=O)O',
 'C1=CC=C(C(=C1)C(=O)O)O',
 'CC1=CC=CC=C1N2CCN(CC2)CCC3=NN=C4N3CCCC4',
 'CC1=C(C(=CC=C1)C)NC(=O)CN2CCN(CC2)CCCC(C3=CC=C(C=C3)F)C4=CC=C(C=C4)F',
 'CNCC(C1=CC(=CC=C1)NS(=O)(=O)C)O',
 'C1=CC=C(C=C1)C(C2=CC=CC=C2)S(=O)CC(=O)NO',
 'C1CNCCC1C(C2=CC=CC=C2)(C3=CC=CC=C3)O',
 'CCOC1=CC=C(C=C1)NC(=O)CC(C)O',
 'CCC1(C(=O)NC(=S)NC1=O)CC(=C)C',
 'CN(C)CCCOC1=NN(C2=CC=CC=C21)CC3=CC=CC=C3',
 'C1=CC=C(C=C1)C2=C(OC(=N2)CCC(=O)O)C3=CC=CC=C3',
 'CC(=O)CC(C1=CC=CC=C1)C2=C(C3=CC=CC=C3OC2=O)O',
 'CC(C)NCC(COC1=CC=CC2=CC=CC=C21)O',
 'CC1=CC(=CC=C1)NC2=C(C=NC=C2)S(=O)(=O)NC(=O)NC(C)C',
 'C1=C(N=C(S1)N=C(N)N)CSCC/C(=N/S(=O)(=O)N)/N',
 'C1=CC(=CC=C1CCN)O',
 'CN(CC(=O)O)C(=S)C1=CC=CC2=C1C=CC(=C2C(F)(F)F)OC',
 'C1=CC=C(C=C1)C(C2=CC=CC=C2)S(=O)CC(=O)N',
 'C1C(=O)N(C2=C(C=C(C=C2)Cl)C(=N1)C3=CC=CC=C3)CC(F)(F)F',
 'C1C(OC2=CC=CC=C2O1)CN=C(N)N',
 'CN1CCN2C3=C(C=C(C=C3)OC)C4=C2C1=NCC4',
 'C1=CC=C(C(=C1)C2=NC(C(=O)NC3=C2C=C(C=C3)Cl)O)Cl',
 'C1=CC=C(C(=C1)C(=O)O)OP(=O)(O)O',
 'CNS(=O)(=O)CC1=CC2=C(C=C1)NC=C2CCN(C)C',
 'CC(=O)NC1=CC=C(C=C1)O',
 'COC1=C(C=C(C=C1)Cl)C(=O)NCCC2=CC=C(C=C2)S(=O)(=O)NC(=O)NC3CCCCC3',
 'CC(C)NCC(COC1=CC=CC2=C1C=CN2)O',
 'CC1=CC=C(C=C1)S(=O)(=O)NC(=O)NN2CCCCCC2',
 'C1CN(CCC1N2C3=CC=CC=C3NC2=O)CCCC(=O)C4=CC=C(C=C4)F',
 'CS(=O)(=O)C1=CC2=C(C=C1)SC3=CC=CC=C3N2CCCN4CCC(CC4)C(=O)N',
 'C1=CN=CC=C1C(=O)NN',
 'CCC1(C(=O)NC(=O)NC1=O)C2=CCCCCC2',
 'CS(=O)(=O)OCCC(=O)N1CCN(CC1)C(=O)CCOS(=O)(=O)C',
 'CC(=C)CN1C(=CC(=O)N(C1=O)C)N',
 'CCC1(C(=O)NC(=O)N(C1=O)C)C2=CC=CC=C2',
 'CC1(C(=O)C=C(O1)C(=O)O)C2=CC=CC=C2',
 'CC(C)C1(C(=O)NC(=O)NC1=O)CC(=C)Br',
 'CC(C1=CC=C(C=C1)C2CCCC(=NO)C2)C(=O)O',
 'CCN1CCCC1CNC(=O)C2=C(C=CC(=C2)S(=O)(=O)N)OC',
 'CC1=C(N(C(=C1)CC(=O)O)C)C(=O)C2=CC=C(C=C2)Cl',
 'CN1CC(C2=C(C1)C(=CC=C2)N)C3=CC=CC=C3',
 'C[C@H](CN1CCOCC1)C(C2=CC=CC=C2)(C3=CC=CC=C3)C(=O)N4CCCC4',
 'CCC1=C(NC2=C1C(=O)C(CC2)CN3CCOCC3)C',
 'C1CCS(=O)(=O)N(C1)C2=CC=C(C=C2)S(=O)(=O)N',
 'CCCCC1=NC2(CCCC2)C(=O)N1CC3=CC=C(C=C3)C4=CC=CC=C4C5=NNN=N5',
 'C1=CC(=CC=C1C#N)C(C2=CC=C(C=C2)C#N)N3C=NC=N3',
 'C1=CC(=O)N(C=C1)C2=CC=CC(=C2)N',
 'C1=CC2=C(C=C1Cl)N=C(O2)N',
 'C1COC2(N1CC(=O)NC3=C2C=C(C=C3)Br)C4=CC=CC=C4F',
 'CC(C)(C(=O)O)OC1=CC=C(C=C1)CCNC(=O)C2=CC=C(C=C2)Cl',
 'CC1CN2CC(=O)NC3=C(C2(O1)C4=CC=CC=C4)C=C(C=C3)Cl',
 'ERROR',
 'CC(=O)C1=CC=C(C=C1)S(=O)(=O)NC(=O)NC2CCCCC2',
 'COC1=C(C=C(C=C1)/C=N/NC(=O)C2=CC=NC=C2)OC',
 'CC1=CC(=NO1)C(=O)NCCC2=CC=C(C=C2)S(=O)(=O)NC(=O)NN3CCCCCC3',
 'C1=CN=C(C=N1)C(=O)N',
 'C1CN(CCC12C(=O)NCN2C3=CC=CC=C3)CCCC(=O)C4=CC=C(C=C4)F',
 'C1=CC=C2C(=C1)C=CC3=CC=CC=C3N2C(=O)N',
 'CC1=CC=C(C=C1)S(=O)(=O)NC(=O)N[C@H]2[C@H]3CC[C@@]([C@H]2O)(C3(C)C)C',
 'COC1=CC(=C(C=C1C(=O)NC2CCN(CC2)CC3=CC=CC=C3)Cl)N',
 'C1=CC(=CC=C1N)S(=O)(=O)C2=CC=C(C=C2)NCC(=O)O',
 'CC1=CC(=O)OC2=C1C=CC(=C2)O',
 'CC(=O)N[C@@H](CCC(=O)N)C(=O)O',
 'C1=CC=C2C(=C1)C(=NN(C2=O)CC3=NC4=C(S3)C=CC(=C4)C(F)(F)F)CC(=O)O',
 'CCCN(CCC)S(=O)(=O)C1=CC=C(C=C1)C(=O)O',
 'CN1C(=C(C2=CC=CC=C2S1(=O)=O)O)C(=O)NC3=CC=CC=N3',
 'C/C(=N\\NC(=O)C1=CC=NC=C1)/C2=CC=CO2',
 'C[C@H](CCC(=O)O)[C@H]1CC[C@@H]2[C@@]1(CC[C@H]3[C@H]2[C@H](C[C@H]4[C@@]3(CC[C@H](C4)O)C)O)C',
 'C1C2=CC=CC=C2OC(=O)N1CC(=O)N',
 'C1=CC=C(C=C1)C2=NC(C(=O)NC3=C2C=C(C=C3)Cl)O',
 'C1=CC=C2C(=C1)C(=NN2CC3=C(C=C(C=C3)Cl)Cl)C(=O)O',
 'C1CN(CCC1NC(=O)C2=CC=CC=C2)CCC3=CNC4=CC=CC=C43',
 'CCCSC1=CC2=C(C=C1)N=C(N2)NC(=O)OC',
 'C=CC(CCC(=O)O)N',
 'C[C@]([C@H]1C[C@@]23CC[C@@]1([C@H]4[C@@]25CCN([C@@H]3CC6=C5C(=C(C=C6)O)O4)CC7CC7)OC)(C(C)(C)C)O',
 'CC(C)CC1C(=O)N(C(=S)N1)CC=C',
 'ERROR',
 'C[C@@H]1CC(=O)C=C([C@]12C(=O)C3=C(O2)C(=C(C=C3OC)OC)Cl)OC',
 'CCCCS(=O)(=O)N[C@@H](CC1=CC=C(C=C1)OCCCCC2CCNCC2)C(=O)O',
 'C[C@]12CCC(=O)C=C1CC[C@@H]3[C@@H]2[C@H](C[C@]4([C@H]3CC[C@@]4(C(=O)CO)O)C)O',
 'ERROR',
 'CC(C)NC1=C(N=CC=C1)N2CCN(CC2)C(=O)C3=CC4=C(N3)C=CC(=C4)NS(=O)(=O)C',
 'CC1=CC(=C(C(=C1/C=C/C(=C/C=C/C(=C/C(=O)O)/C)/C)C)C)OC',
 'CCCC1C(=O)N2C3=C(C=CC(=C3)C)N=C(N2C1=O)N(C)C',
 'CCCOC1=CC2=C(C=C1)N=C(N2)NC(=O)OC',
 'CC1=NC=CN1CC2CCC3=C(C2=O)C4=CC=CC=C4N3C',
 'CC(C)C[C@@H](C(=O)O)NC(=O)[C@H]([C@@H](CC1=CC=CC=C1)N)O',
 'C1=CC=C(C=C1)C2C(=O)NN(C2=O)C3=CC=CC=C3',
 'COC1=C(C=C(C=C1)CC2=CN=C(N=C2N)N)OC',
 'C1=CC(=CC=C1NC2=NC=NC(=N2)N)Cl',
 'CC1=NC(=NC=C1)NS(=O)(=O)C2=CC=C(C=C2)N',
 'COC(=O)[C@H]1[C@H](CC[C@@H]2[C@@H]1C[C@H]3C4=C(CCN3C2)C5=CC=CC=C5N4)O',
 'C1=CC=C2C(=C1)C=CN3C2=NC(=N3)C4=CC=C(C=C4)Cl',
 'CS(=O)(=O)C1=CC=C(C=C1)C2=CN3C=CC=CC3=N2',
 'CC1=C(C2=C(N1CC(=O)O)C=C(C=C2)OC)C(=O)C3=CC=C(C=C3)Cl',
 'C1CC(C2=C(C3=CC=CC=C3N=C2C1)N)O',
 'C1=CC(=C(C(=C1)Cl)CN2C=NC3=C(N=CN=C32)N)F',
 'CC1NC2=CC(=C(C=C2C(=O)N1C3=CC=CC=C3C)S(=O)(=O)N)Cl',
 'CC1CCC2=C3N1C=C(C(=O)C3=CC(=C2)F)C(=O)O',
 'C1=NC2=C(N1COCCO)N=C(NC2=O)N',
 'ERROR',
 'C1CC1N2C=C(C(=O)C3=CC(=C(C=C32)N4CCNCC4)F)C(=O)O',
 'C1NC2=CC(=C(C=C2S(=O)(=O)N1)S(=O)(=O)N)Cl',
 'CC1CCC2=C3N1C=C(C(=O)C3=CC(=C2C)F)C(=O)O',
 'C[C@H]1COC2=C3N1C=C(C(=O)C3=CC(=C2C4(CC4)N)F)C(=O)O',
 'CN1C2=C(C(=O)N(C1=O)C)NC=N2',
 'CN1C2=C(C(=O)N(C1=O)C)N(C=N2)CC(=O)O',
 'C1NC2=C(C=C(C(=C2)C(F)(F)F)S(=O)(=O)N)S(=O)(=O)N1',
 'ERROR',
 'CCC1(C(=O)NCNC1=O)C2=CC=CC=C2',
 'COC1=C(C=C2C(=C1)C(=NC(=N2)N3CCN(CC3)C(=O)C4=CC=CO4)N)OC',
 'CC(=O)NC1=CC=C(C=C1)S(=O)(=O)C2=CC=C(C=C2)NC(=O)C',
 'C1=CC=C(C=C1)C2(C(=O)NC(=O)N2)C3=CC=CC=C3',
 'C1=C(NC(=O)NC1=O)C(=O)O']

In [10]:
data['SMILES'] = isomeric_smiles

In [11]:
data.head()

,NAME,MELTING POINT,ID,SMILES
0,buramate,40.0,[Compound(20787)],C1=CC=C(C=C1)CNC(=O)OCCO
1,fenpiprane,41.0,[Compound(197785)],C1CCN(CC1)CCC(C2=CC=CC=C2)C3=CC=CC=C3
2,trimipramine,45.0,[Compound(5584)],CC(CN1C2=CC=CC=C2CCC3=CC=CC=C31)CN(C)C
3,phencarbamide,48.0,[Compound(6008)],CCN(CC)CCSC(=O)N(C1=CC=CC=C1)C2=CC=CC=C2
4,banactyzine,51.0,[],ERROR

In [12]:
to_be_added_manually = data[data['SMILES'] == 'ERROR']

In [13]:
to_be_added_manually

                     NAME  MELTING POINT  ID SMILES
4             banactyzine           51.0  []  ERROR
38             alc1ofenac           92.0  []  ERROR
45             tamoxi fen           96.0  []  ERROR
106           erytromycin          135.0  []  ERROR
127             felodipin          145.0  []  ERROR
141              abecamil          150.0  []  ERROR
214       acetoaminosalol          187.0  []  ERROR
239             methetion          210.0  []  ERROR
243  Melengestroleacetate          224.0  []  ERROR
263            skfl 05657          257.0  []  ERROR
271            moxesterol          280.0  []  ERROR

In [14]:
manually_adding = {'banactyzine': 'CCN(CC)CCOC(=O)C(C1=CC=CC=C1)(C2=CC=CC=C2)O', #correct name banactyzine
                  'alc1ofenac': 'C=CCOC1=C(C=C(C=C1)CC(=O)O)Cl', #alclofenac
                  'tamoxi fen': 'CCC(=C(C1=CC=CC=C1)C2=CC=C(C=C2)OCCN(C)C)C3=CC=CC=C3', #tamoxifen
                  'erytromycin': 'CC[C@@H]1[C@@]([C@@H]([C@H](C(=O)[C@@H](C[C@@]([C@@H]([C@H]([C@@H]([C@H](C(=O)O1)C)O[C@H]2C[C@@]([C@H]([C@@H](O2)C)O)(C)OC)C)O[C@H]3[C@@H]([C@H](C[C@H](O3)C)N(C)C)O)(C)O)C)C)O)(C)O', #erytromycin
                  'felodipin': 'CCOC(=O)C1=C(N(C(=C(C1C2=C(C(=CC=C2)Cl)Cl)C(=O)OC)C)C=O)C', #felodipin
                  'abecamil': "CC(C)OC(=O)C1=NC=C2C(=C1COC)C3=C(N2)C=CC(=C3)OCC4=CC=CC=C4", #abecamil, Abecarnil
                  'acetoaminosalol': 'CC(=O)NC1=CC=C(C=C1)OC(=O)C2=CC=CC=C2O', #acetoaminosalol para-acetylammophenyl salicylate. #https://pubchem.ncbi.nlm.nih.gov/compound/1984
                  'methetion': 'CCC1(N(C)C(=O)NC1=O)c2ccccc2', #methetion
                  'Melengestroleacetate': 'CC1=C[C@@H]2[C@H](CC[C@]3([C@H]2CC(=C)[C@@]3(C(=O)C)OC(=O)C)C)[C@@]4(C1=CC(=O)CC4)C', #Melengestroleacetate
                  'skfl 05657': 'C[C@]12CC[C@H]3[C@H]([C@@H]1CC[C@@H]2C(=O)NC(C)(C)C)CC=C4[C@@]3(CCC(=C4)C(=O)O)C', #skf105657  l or 1
                  'moxesterol': 'C[C@]12C[C@@H]([C@H]3[C@H]([C@@H]1CC[C@]2(C#C)O)CCC4=C3C=CC(=C4)O)OC'}

In [15]:
manually_adding

{'banactyzine': 'CCN(CC)CCOC(=O)C(C1=CC=CC=C1)(C2=CC=CC=C2)O',
 'alc1ofenac': 'C=CCOC1=C(C=C(C=C1)CC(=O)O)Cl',
 'tamoxi fen': 'CCC(=C(C1=CC=CC=C1)C2=CC=C(C=C2)OCCN(C)C)C3=CC=CC=C3',
 'erytromycin': 'CC[C@@H]1[C@@]([C@@H]([C@H](C(=O)[C@@H](C[C@@]([C@@H]([C@H]([C@@H]([C@H](C(=O)O1)C)O[C@H]2C[C@@]([C@H]([C@@H](O2)C)O)(C)OC)C)O[C@H]3[C@@H]([C@H](C[C@H](O3)C)N(C)C)O)(C)O)C)C)O)(C)O',
 'felodipin': 'CCOC(=O)C1=C(N(C(=C(C1C2=C(C(=CC=C2)Cl)Cl)C(=O)OC)C)C=O)C',
 'abecamil': 'CC(C)OC(=O)C1=NC=C2C(=C1COC)C3=C(N2)C=CC(=C3)OCC4=CC=CC=C4',
 'acetoaminosalol': 'CC(=O)NC1=CC=C(C=C1)OC(=O)C2=CC=CC=C2O',
 'methetion': 'CCC1(N(C)C(=O)NC1=O)c2ccccc2',
 'Melengestroleacetate': 'CC1=C[C@@H]2[C@H](CC[C@]3([C@H]2CC(=C)[C@@]3(C(=O)C)OC(=O)C)C)[C@@]4(C1=CC(=O)CC4)C',
 'skfl 05657': 'C[C@]12CC[C@H]3[C@H]([C@@H]1CC[C@@H]2C(=O)NC(C)(C)C)CC=C4[C@@]3(CCC(=C4)C(=O)O)C',
 'moxesterol': 'C[C@]12C[C@@H]([C@H]3[C@H]([C@@H]1CC[C@]2(C#C)O)CCC4=C3C=CC(=C4)O)OC'}

In [16]:
to_be_added_manually = to_be_added_manually.reset_index()

In [17]:
to_be_added_manually

    index                  NAME  MELTING POINT  ID SMILES
0       4           banactyzine           51.0  []  ERROR
1      38            alc1ofenac           92.0  []  ERROR
2      45            tamoxi fen           96.0  []  ERROR
3     106           erytromycin          135.0  []  ERROR
4     127             felodipin          145.0  []  ERROR
5     141              abecamil          150.0  []  ERROR
6     214       acetoaminosalol          187.0  []  ERROR
7     239             methetion          210.0  []  ERROR
8     243  Melengestroleacetate          224.0  []  ERROR
9     263            skfl 05657          257.0  []  ERROR
10    271            moxesterol          280.0  []  ERROR

In [18]:
to_be_added_manually['SMILES'] = manually_adding.values()

In [19]:
to_be_added_manually

,index,NAME,MELTING POINT,ID,SMILES
0,4,banactyzine,51.0,[],CCN(CC)CCOC(=O)C(C1=CC=CC=C1)(C2=CC=CC=C2)O
1,38,alc1ofenac,92.0,[],C=CCOC1=C(C=C(C=C1)CC(=O)O)Cl
2,45,tamoxi fen,96.0,[],CCC(=C(C1=CC=CC=C1)C2=CC=C(C=C2)OCCN(C)C)C3=CC...
3,106,erytromycin,135.0,[],CC[C@@H]1[C@@]([C@@H]([C@H](C(=O)[C@@H](C[C@@]...
4,127,felodipin,145.0,[],CCOC(=O)C1=C(N(C(=C(C1C2=C(C(=CC=C2)Cl)Cl)C(=O...
5,141,abecamil,150.0,[],CC(C)OC(=O)C1=NC=C2C(=C1COC)C3=C(N2)C=CC(=C3)O...
6,214,acetoaminosalol,187.0,[],CC(=O)NC1=CC=C(C=C1)OC(=O)C2=CC=CC=C2O
7,239,methetion,210.0,[],CCC1(N(C)C(=O)NC1=O)c2ccccc2
8,243,Melengestroleacetate,224.0,[],CC1=C[C@@H]2[C@H](CC[C@]3([C@H]2CC(=C)[C@@]3(C...
9,263,skfl 05657,257.0,[],C[C@]12CC[C@H]3[C@H]([C@@H]1CC[C@@H]2C(=O)NC(C...
10,271,moxesterol,280.0,[],C[C@]12C[C@@H]([C@H]3[C@H]([C@@H]1CC[C@]2(C#C)...

In [20]:
for i in range(len(data)):
    for x in range(len(to_be_added_manually)):
        if to_be_added_manually['NAME'][x] == data['NAME'][i]:
            data['SMILES'][i] = to_be_added_manually['SMILES'][x]
            print(to_be_added_manually['NAME'][x])
        else:
            pass

banactyzine
alc1ofenac
tamoxi fen
erytromycin
felodipin
abecamil
acetoaminosalol
methetion
Melengestroleacetate
skfl 05657
moxesterol

<ipython-input-20-05c7b6eb922c>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['SMILES'][i] = to_be_added_manually['SMILES'][x]

In [21]:
data.loc[data['SMILES'] == 'ERROR']

Empty DataFrame
Columns: [NAME, MELTING POINT, ID, SMILES]
Index: []

In [22]:
to_be_printed = data[['SMILES', 'MELTING POINT']]

In [23]:
to_be_printed = to_be_printed.rename(columns={'SMILES': 'SMILES', 'MELTING POINT': 'target_0' })

In [24]:
to_be_printed.head()

                                        SMILES  target
0                     C1=CC=C(C=C1)CNC(=O)OCCO    40.0
1        C1CCN(CC1)CCC(C2=CC=CC=C2)C3=CC=CC=C3    41.0
2       CC(CN1C2=CC=CC=C2CCC3=CC=CC=C31)CN(C)C    45.0
3     CCN(CC)CCSC(=O)N(C1=CC=CC=C1)C2=CC=CC=C2    48.0
4  CCN(CC)CCOC(=O)C(C1=CC=CC=C1)(C2=CC=CC=C2)O    51.0

In [25]:
to_be_printed.to_csv('data.csv')

## AGG

In [1]:
import pandas as pd
import numpy as np
data_ = pd.read_csv('data.csv')
data_.head()

   Unnamed: 0                                       SMILES  target
0           0                     C1=CC=C(C=C1)CNC(=O)OCCO    40.0
1           1        C1CCN(CC1)CCC(C2=CC=CC=C2)C3=CC=CC=C3    41.0
2           2       CC(CN1C2=CC=CC=C2CCC3=CC=CC=C31)CN(C)C    45.0
3           3     CCN(CC)CCSC(=O)N(C1=CC=CC=C1)C2=CC=CC=C2    48.0
4           4  CCN(CC)CCOC(=O)C(C1=CC=CC=C1)(C2=CC=CC=C2)O    51.0

In [2]:
data_['SMILES'].describe()

count                                    277
unique                                   277
top       CC1=CC(=C(C=C1)C)OCCCC(C)(C)C(=O)O
freq                                       1
Name: SMILES, dtype: object